[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
db = { path = "../db" }
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
