[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
shared = { path = "../shared" }
csv = "1.3.0"
chrono = "0.4.38"
